travis:
  secure:
    BINSTAR_TOKEN: 4spIAwTF7wjjmqsRiPEglFyS/nO6Pvo3Pv40vJ/zyoCQi4YtEOK21KLMj8k7Ev+lXJSErxopKorz4YmHgUJJuAuLP1GlOtitG2VXz4F8jNpi8QoCgw0tixZ1Z/xT+UXe0ovW37CpXC/tuytGRlz/t+0FlhxWnJrURsU6fEbT8r0/wMvq0D0z/juFGk4VvoxL3mEY1A/Fh4zox5HGWzFWL4F4hhucOatm8XMWrj02Nf6osX+anRLJHqU8GmTsVQ7yxZR+1uwhVQEgVxjR3h5xZmQ88ksC+7OBIuAjT6opIzLnrXzjn73DPuvIa8YV4c7FwgKC51lA5gT8rdVIr3oHG9I3E9430mBWPtOUTQVyC2py1+5DbgsHyOP7hSQrhYKyykmN5iCc2A/RtEgsiKhcp0sZBvU/gR++SLYbBx4sUpYqxIXs7GbRdQuXoruWzQ1QilAyq38s0viSMKN6GxcQz+w2vtMak/IPJZkH4i5ukNvpWQ8NUamC0VBixRJcrDWTMqwV5fOu+a23SFRFz7Dvv2X3ElhfIA8u09vR/ZSG3CITI2w3eOptUN12CTJz9+f6/sTkpGZrMbRQlU1ZishwkNVrB+KDB2IlCcyM7HhZEExxOAEYb17znCw8mIFfZgeGjlKiSm8H8EksPNOE8R7awW5sniGCA6p2uQDUebDTxaY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
